apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: production
spec:
  kind: Permanent
  label: Production
  namespace: jx-vet-production
  order: 200
  previewGitInfo:
    user: {}
  promotionStrategy: Manual
  source:
    ref: master
    url: https://github.com/vet-bot/environment-wyrmheavy-production.git
  teamSettings:
    defaultScheduler:
      kind: ""
      name: ""
status: {}
